version: '3.8'
services:
    db:
        container_name: animaltinder-database
        image: mysql
        restart: always
        environment:
            MYSQL_USER: rootD3nkQxZnG
            MYSQL_ROOT_PASSWORD: vhG4UEhAMfucguTx
            MYSQL_DATABASE: animalTinder
            MYSQL_PASSWORD: 862cMuAkp3u3ZHKc
        networks:
            - animaltindernetwork
    phpmyadmin:
        container_name: animaltinder-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        networks:
            - animaltindernetwork
        environment:
            PMA_HOST: animaltinder-database
            PMA_PORT: 3306
        depends_on:
            - db
    php-apache-environment:
        container_name: animaltinder-phpapacha
        restart: always
        build:
            context: ./php
            dockerfile: Dockerfile
        networks:
            - animaltindernetwork
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
networks:
    animaltindernetwork:
